# Build and Test

name: Build and Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test-xcode:
    strategy:
      matrix:
        xcode-version:
          - "16"
        xcode-configuration:
          - name: iOS Simulator
            destination: "platform=iOS Simulator,name=iPhone 16"
            sdk: "iphonesimulator"
          - name: macOS
            destination: "platform=macOS"
            sdk: "macosx"
        swift-configuration:
          - "debug"
          - "release"
    
    runs-on: macos-15
    
    name: Build and Test (${{ matrix.xcode-configuration.name}}, ${{ matrix.swift-configuration }})

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer

      - name: Build
        run: |
          xcrun xcodebuild clean build \
            -workspace Xcode/SwiftProjectTemplateApp.xcworkspace \
            -scheme SwiftProjectTemplateApp \
            -derivedDataPath ".build/Xcode.noindex/DerivedData" \
            -configuration "${{ matrix.swift-configuration }}" \
            -sdk "${{ matrix.xcode-configuration.sdk }}" \
            -destination "${{ matrix.xcode-configuration.destination }}"

      - name: Test
        run: |
          xcrun xcodebuild test \
            -workspace Xcode/SwiftProjectTemplateApp.xcworkspace \
            -scheme SwiftProjectTemplateAppUITests \
            -derivedDataPath ".build/Xcode.noindex/DerivedData" \
            -configuration "${{ matrix.swift-configuration }}" \
            -sdk "${{ matrix.xcode-configuration.sdk }}" \
            -destination "${{ matrix.xcode-configuration.destination }}"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (${{ matrix.xcode-configuration.name }}, ${{ matrix.swift-configuration }})
          path: .build/Xcode.noindex/DerivedData/Logs/Test
      
      - name: Check that repository is clean
        run:
          git diff --exit-code

  build-and-test-devcontainer:

    strategy:
      matrix:
        devcontainer-name: ["default"]
        swift-configuration: ["debug", "release"]

    name: Build and Test (devcontainer/${{ matrix.devcontainer-name }}, ${{ matrix.swift-configuration }})

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make devcontainer '${{ matrix.devcontainer-name }}' singular
        run: .devcontainer/devcontainer-helper --make-singular ${{ matrix.devcontainer-name }}
      
      - name: Initialize devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            echo "Devcontainer Initialized."
      
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            swift build --configuration ${{ matrix.swift-configuration }}

      - name: Build Tests
        if: matrix.swift-configuration == 'debug'
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            swift build --build-tests --configuration ${{ matrix.swift-configuration }}

      - name: Test
        uses: devcontainers/ci@v0.3
        if: matrix.swift-configuration == 'debug'
        with:
          push: never
          runCmd: |
            swift test --skip-build
    
      - name: Check that repository is clean
        run:
          .devcontainer/devcontainer-helper --clean
          git diff --exit-code